# Generated by Django 4.1.2 on 2023-01-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_bd_name', models.CharField(blank=True, max_length=40, null=True)),
                ('add_bd_dsc', models.CharField(blank=True, max_length=100, null=True)),
                ('add_bd_profile', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_ct_name', models.CharField(blank=True, max_length=40, null=True)),
                ('add_ct_dsc', models.CharField(blank=True, max_length=100, null=True)),
                ('add_ct_profile', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_pdt_category', models.CharField(blank=True, max_length=40, null=True)),
                ('add_pdt_brand', models.CharField(blank=True, max_length=40, null=True)),
                ('add_pdt_name', models.CharField(blank=True, max_length=40, null=True)),
                ('add_pdt_dsc', models.CharField(blank=True, max_length=100, null=True)),
                ('add_pdt_size', models.CharField(blank=True, max_length=40, null=True)),
                ('add_pdt_price', models.CharField(blank=True, max_length=40, null=True)),
                ('add_pdt_profile_1', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('add_pdt_profile_2', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('add_pdt_profile_3', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='sizedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_ltr', models.CharField(blank=True, max_length=40, null=True)),
                ('size_num', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
