# Generated by Django 4.1.2 on 2023-01-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizedb',
            name='size_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
