# Generated by Django 4.1.5 on 2023-01-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('pdt_name', models.CharField(blank=True, max_length=40, null=True)),
                ('pdt_brand', models.CharField(blank=True, max_length=40, null=True)),
                ('pdt_price', models.IntegerField(blank=True, max_length=40, null=True)),
                ('pdt_quantity', models.CharField(blank=True, max_length=40, null=True)),
                ('pdt_total', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
