# Generated by Django 4.1.5 on 2023-01-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_cartdb_pdt_price_alter_cartdb_pdt_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdb',
        ),
    ]
